export enum ChainKey {
  ASTROL = 'astrol',
  BOBA = 'boba',
  CAMELOT = 'camelot',
  DINERO = 'dinero',
  ECLIPSE = 'eclipse',
  ETHEREUM = 'ethereum',
  FORM = 'form',
  INVARIANT = 'invariant',
  JELLYVERSE = 'jellyverse',
  LENDLAND = 'lendland',
  LYNX = 'lynx',
  NEPTUNE = 'neptune',
  OKU = 'oku',
  ORCA = 'orca',
  PLUME = 'plume',
  RARI = 'rari',
  SANDGLASS = 'sandglass',
  SAVE = 'save',
  SEI = 'sei',
  SWELL = 'swell',
  SUPRA = 'supra',
  TEAHOUSE = 'teahouse',
  UNIFI = 'UniFi',
  YEI = 'yei',
}
