export enum ChainKey {
  BOBA = 'boba',
  ETHEREUM = 'ethereum',
  SEI = 'sei',
  SWELL = 'swell',
  ECLIPSE = 'eclipse',
  RARI = 'rari',
  DINERO = 'dinero',
  FORM = 'form',
  UNIFI = 'UniFi',
  ORCA = 'orca',
  INVARIANT = 'invariant',
  SAVE = 'save',
  ASTROL = 'astrol',
  JELLYVERSE = 'jellyverse',
  YEI = 'yei',
  CAMELOT = 'camelot',
}
