export enum TokenKey {
  ETH = 'eth',
  WETH = 'weth',
  WEETH = 'weeth',
  WSTETH = 'wsteth',
  SEI = 'sei',
  RSETH = 'rseth',
  RSWETH = 'rsweth',
  EZETH = 'ezeth',
  OP = 'op',
  FRAX = 'frax',
  WBTC = 'wbtc',
  SWBTC = 'swbtc',
  RSWBTC = 'rswbtc',
  WFRXETH = 'wfrxeth',
}
