export enum TokenKey {
  ETH = 'eth',
  EZETH = 'ezeth',
  OP = 'op',
  RSETH = 'rseth',
  RSWBTC = 'rswbtc',
  EARNBTC = 'earnbtc',
  RSWETH = 'rsweth',
  SEIYANETH = 'seiyaneth',
  SSETH = 'sseth',
  SWBTC = 'swbtc',
  WBTC = 'wbtc',
  WEETH = 'weeth',
  WETH = 'weth',
  WSTETH = 'wsteth',
}
