export enum TokenKey {
  APXETH = 'apxeth',
  DINERO = 'dinero',
  EARNBTC = 'earnbtc',
  EARNETH = 'earneth',
  ETH = 'eth',
  EZETH = 'ezeth',
  FETH = 'feth',
  OP = 'op',
  PUFETH = 'pufeth',
  RSETH = 'rseth',
  RSWBTC = 'rswbtc',
  RSWETH = 'rsweth',
  SEI = 'sei',
  SEIYANETH = 'seiyaneth',
  SFRXETH = 'sfrxeth',
  SSETH = 'sseth',
  SWBTC = 'swbtc',
  TETH = 'teth',
  WBTC = 'wbtc',
  WEETH = 'weeth',
  WETH = 'weth',
  WSTETH = 'wsteth',
}
