export const docsUrl = 'https://docs.nucleusearn.io/'
export const discordUrl = 'https://discord.com/invite/CjQqUgPA6Y'
export const nativeAddress = '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE'
export const atomicQueueContractAddress = '0xc7287780bfa0C5D2dD74e3e51E238B1cd9B221ee'
export const etherscanBaseUrl = 'https://etherscan.io'
export const seiExplorerBaseUrl = 'https://seitrace.com'
export const rariExplorerBaseUrl = 'https://mainnet.explorer.rarichain.org'
export const layerZeroBaseUrl = 'https://layerzeroscan.com'
export const eclipseRpcUrl = 'https://mainnetbeta-rpc.eclipse.xyz'
export const redstoneBaseUrl = 'https://api.redstone.finance/'
export const nucleusBackendBaseUrl = 'https://nucleus-backend-pi.vercel.app/'
export const nucleusApiBaseUrl = 'https://api.nucleusearn.io/'
export const hardcodedApy = 4 // 4%
export const msInOneYear = 31_556_952_000
export const mintSlippage = 0.005 // 0.5%
export const redeemFee = 0.2 // 0.2%
export const pollBalanceInterval = 30_000 // 30 seconds
export const pollBalanceAfterTransactionInterval = 10_000 // 10 seconds
export const pollBalanceAfterTransactionAttempts = 12 // 2 minutes worth of attempts
export const hyperlaneIdForEclipse = 1408864445
