export const docsUrl = 'https://docs.nucleusearn.io/'
export const discordUrl = 'https://discord.com/invite/CjQqUgPA6Y'
export const nativeAddress = '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE'
export const atomicQueueContractAddress = '0x228c44bb4885c6633f4b6c83f14622f37d5112e5'
export const etherscanBaseUrl = 'https://etherscan.io'
export const seiExplorerBaseUrl = 'https://seitrace.com'
export const rariExplorerBaseUrl = 'https://mainnet.explorer.rarichain.org'
export const swellExplorerBaseURL = 'https://explorer.swellnetwork.io'
export const bobaExplorerBaseURL = 'https://bobascan.com'
export const formExplorerBaseUrl = 'https://explorer.form.network'
export const layerZeroBaseUrl = 'https://layerzeroscan.com'
export const hyperlaneBaseUrl = 'https://explorer.hyperlane.xyz'
export const eclipseRpcUrl = 'https://mainnetbeta-rpc.eclipse.xyz'
export const redstoneBaseUrl = 'https://api.redstone.finance/'
export const nucleusBackendBaseUrl = 'https://nucleus-backend-pi.vercel.app/'
export const nucleusApiBaseUrl = 'https://api.nucleusearn.io/'
export const supraScanBaseUrl = 'https://suprascan.io/tx/'
export const hardcodedApy = 4 // 4%
export const msInOneYear = 31_556_952_000
export const mintSlippage = 0.005 // 0.5%
export const defaultWithdrawSlippage = 0.2 // 0.2%
export const pollBalanceInterval = 30_000 // 30 seconds
export const pollBalanceAfterTransactionInterval = 10_000 // 10 seconds
export const pollBalanceAfterTransactionAttempts = 12 // 2 minutes worth of attempts
export const hyperlaneIdForEclipse = 1408864445
