export const docsUrl = 'https://docs.nucleusearn.io/'
export const discordUrl = 'https://discord.com/invite/CjQqUgPA6Y'
export const nativeAddress = '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE'
export const etherscanBaseUrl = 'https://etherscan.io/address/'
export const layerZeroBaseUrl = 'https://layerzeroscan.com/tx/'
export const hardcodedApy = 4 // 4%
export const msInOneYear = 31_556_952_000
export const mintSlippage = 0.005 // 0.5%
export const pollBalanceInterval = 30_000 // 30 seconds
